source 'https://github.com/CocoaPods/Specs.git'

target 'GoogleMapsSwiftDemos' do
    platform :ios, '12.0'
    pod 'GoogleMaps', '= 6.0.1'
    pod 'Alamofire', '~> 5.5'
    pod 'SwiftyJSON', '~> 5.0.0'
end
